/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"

@class NSString, UIImageView;

@interface LanguageCell : PSTableCell {
@private
	UIImageView* _languageNameImage;
	NSString* _languageNameText;
}
@property(retain, nonatomic) NSString* languageNameText;
@property(retain, nonatomic) UIImageView* languageNameImage;
-(void)dealloc;
-(void)prepareForReuse;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setChecked:(BOOL)checked;
-(void)turnOffLanguageNameImage;
@end

