/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <UIKit/UILabel.h>
#import "Preferences-Structs.h"

@class NSURL;

@interface PrefsUILinkLabel : UILabel {
	NSURL* _url;
	BOOL _touchingURL;
	id _target;
	SEL _action;
@private
	NSURL* _URL;
}
@property(assign, nonatomic) SEL action;
@property(assign, nonatomic) id target;
@property(retain, nonatomic) NSURL* URL;
-(id)color:(id)color byMultiplyingSubComponentsBy:(float)by;
-(void)tappedLink:(id)link;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)openURL:(id)url;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

