/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/Foundation.h>

@class PSListController;

@interface PSBundleController : NSObject {
	PSListController* _parent;
}
-(id)initWithParentListController:(id)parentListController;
-(id)specifiersWithSpecifier:(id)specifier;
-(void)unload;
-(void)load;
@end

