/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#include <Foundation/Foundation.h>

@protocol PSController <NSObject>
-(void)statusBarWillAnimateByHeight:(float)statusBar;
-(BOOL)canBeShownFromSuspendedState;
-(void)willBecomeActive;
-(void)willResignActive;
-(id)readPreferenceValue:(id)value;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(void)handleURL:(id)url;
-(void)pushController:(id)controller;
-(void)didWake;
-(void)didUnlock;
-(void)willUnlock;
-(void)didLock;
-(void)suspend;
-(id)specifier;
-(void)setSpecifier:(id)specifier;
-(id)rootController;
-(void)setRootController:(id)controller;
-(id)parentController;
-(void)setParentController:(id)controller;
@end

