/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSSpecifier.h"

@class NSString;

@interface PSConfirmationSpecifier : PSSpecifier {
	NSString* _title;
	NSString* _prompt;
	NSString* _okButton;
	NSString* _cancelButton;
}
@property(retain, nonatomic) NSString* cancelButton;
@property(retain, nonatomic) NSString* okButton;
@property(retain, nonatomic) NSString* prompt;
@property(retain, nonatomic) NSString* title;
+(id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(int)cell edit:(Class)edit;
-(void)dealloc;
-(BOOL)isDestructive;
-(void)setupWithDictionary:(id)dictionary;
@end

