/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"

@class UIControl;

@interface PSControlTableCell : PSTableCell {
	UIControl* _control;
}
@property(retain, nonatomic) UIControl* control;
-(void)controlChanged:(id)changed;
-(id)controlValue;
-(void)dealloc;
-(id)valueLabel;
-(BOOL)canReload;
-(id)newControl;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

