/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"


@interface PSEditableListController : PSListController {
	BOOL _editable;
	BOOL _editingDisabled;
}
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)didLock;
-(void)suspend;
-(BOOL)performDeletionActionForSpecifier:(id)specifier;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)setEditable:(BOOL)editable;
-(void)_setEditable:(BOOL)editable animated:(BOOL)animated;
-(BOOL)editable;
-(void)editDoneTapped;
-(void)pushController:(id)controller;
-(void)viewWillAppear:(BOOL)view;
-(void)setEditingButtonHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)_updateNavigationBar;
-(id)_editButtonBarItem;
-(id)init;
@end

