/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <UIKit/UIView.h>


@interface PSGradientView : UIView {
}
+(Class)layerClass;
-(id)initWithFrame:(CGRect)frame;
@end

