/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSListItemsController.h"
#import "Preferences-Structs.h"


@interface PSInternationalLanguageController : PSListItemsController {
}
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)specifiers;
-(void)viewWillAppear:(BOOL)view;
-(void)updateNavigationItem;
-(void)doneButtonTapped;
-(void)cancelButtonTapped;
-(void)_removeBlackFrame;
-(id)init;
@end

