/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"

@class NSArray, NSDictionary;

@interface PSInternationalController : PSListController {
	CFLocaleRef _locale;
	double _sampleTime;
	NSArray* _voiceControlTitles;
	NSDictionary* _voiceControlShortTitles;
	NSArray* _voiceControlValues;
}
+(id)voiceControlLanguageData;
+(id)capitalizeFirstPartOfCountry:(id)country;
+(void)setLocale:(id)locale;
+(void)setLanguage:(id)language;
-(id)voiceControlValues:(id)values;
-(id)voiceControlShortTitles;
-(id)voiceControlTitles:(id)titles;
-(void)_initVoiceControlData;
-(id)defaultCalendarForLocale:(id)locale;
-(id)formattedPhoneNumber:(id)number;
-(id)formattedTime:(id)time;
-(id)formattedDate:(id)date;
-(id)calendar:(id)calendar;
-(void)setCalendar:(id)calendar specifier:(id)specifier;
-(id)locale:(id)locale;
-(void)setLocale:(id)locale specifier:(id)specifier;
-(void)setLanguage:(id)language specifier:(id)specifier;
-(id)voiceControlLanguage:(id)language;
-(void)setVoiceControlLanguage:(id)language specifier:(id)specifier;
-(id)localizedLanguage:(id)language;
-(id)language:(id)language;
-(void)showLanguageSheet:(id)sheet;
-(id)specifiers;
-(void)_loadLocaleIfNeeded;
-(void)reloadLocale;
-(void)reloadSpecifiers;
-(id)localizedComponent:(id)component forDictionary:(id)dictionary;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)init;
-(void)localeChangedAction;
@end

