/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/Foundation.h>

@class NSString, NSMutableArray, NSArray;

@interface PSLanguageSelector : NSObject {
	NSString* _language;
	NSMutableArray* _supportedLanguages;
	NSArray* _supportedKeyboards;
}
+(id)sharedInstance;
-(id)supportedLanguages;
-(void)setLanguage:(id)language;
-(id)currentLanguage;
-(void)_loadSupportedLanguages;
-(BOOL)_adjustLanguageIndices;
-(void)_setLanguage:(id)language;
-(void)dealloc;
@end

