/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"

@class PSSpecifier;

@interface PSLocaleController : PSListController {
	PSSpecifier* _checkedSpecifier;
	BOOL _firstAppearance;
}
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)setLocale:(id)locale specifier:(id)specifier;
-(id)locale:(id)locale;
-(id)specifiers;
-(void)addLanguage:(id)language toSupportedLanguages:(id)supportedLanguages;
-(void)viewWillAppear:(BOOL)view;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)subcategorySelected:(id)selected specifier:(id)specifier;
-(void)updateChecked:(id)checked;
-(void)dealloc;
-(id)init;
-(void)localeChangedAction;
@end

