/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSViewController.h"
#include <UIKit/UIKit.h>

@class UITableView;

@interface PSMovableListController : PSViewController <UITableViewDelegate, UITableViewDataSource> {
	UITableView* _tableView;
	CFArrayRef _ordering;
	CFSetRef _disabledDomains;
	BOOL _isDirty;
}
-(void)dealloc;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)_updateCell:(id)cell forDomain:(int)domain;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)viewWillDisappear:(BOOL)view;
-(void)_saveIfNecessary;
-(int)domainForIndexRow:(unsigned)indexRow;
-(id)stringForDomain:(int)domain;
-(id)init;
-(void)_loadEnabledState;
-(void)_loadOrdering;
-(id)displayNameForExtendedDomain:(int)extendedDomain;
-(void)removeUnwantedDomains;
-(void)defaultOrdering;
-(id)keyForDomain:(int)domain;
-(int)domainCount;
-(int)domainForKey:(id)key;
-(id)allDomainKeys;
-(CFStringRef)defaultDomain;
-(CFStringRef)disabledKey;
-(CFStringRef)reorderingKey;
@end

