/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSController.h"
#import <UIKit/UIKit.h>

@class PSSpecifier, NSMutableSet;

@interface PSRootController : UINavigationController <PSController, UINavigationControllerDelegate> {
	PSSpecifier* _specifier;
	NSMutableSet* _tasks;
	BOOL _deallocating;
	unsigned char _hasTelephony;
}
+(BOOL)processedBundle:(id)bundle parentController:(id)controller parentSpecifier:(id)specifier bundleControllers:(id*)controllers settings:(id)settings;
+(id)readPreferenceValue:(id)value;
+(void)setPreferenceValue:(id)value specifier:(id)specifier;
+(void)writePreference:(id)preference;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)setViewControllers:(id)controllers animated:(BOOL)animated;
-(id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;
-(id)popToViewController:(id)viewController animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(void)_delayedControllerReleaseAfterPop:(id)pop;
-(BOOL)canBeShownFromSuspendedState;
-(void)didDismissFormSheetView;
-(void)willDismissFormSheetView;
-(void)didDismissPopupView;
-(void)willDismissPopupView;
-(id)aggregateDictionaryPath;
-(id)rootController;
-(void)setRootController:(id)controller;
-(id)parentController;
-(void)dealloc;
-(BOOL)deallocating;
-(void)didWake;
-(void)didUnlock;
-(void)willUnlock;
-(void)didLock;
-(void)suspend;
-(void)sendWillBecomeActive;
-(void)sendWillResignActive;
-(void)willBecomeActive;
-(void)willResignActive;
-(void)statusBarWillChangeHeight:(id)statusBar;
-(void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;
-(void)handleURL:(id)url;
-(void)pushController:(id)controller;
-(id)specifier;
-(void)setSpecifier:(id)specifier;
-(void)setParentController:(id)controller;
-(void)statusBarWillAnimateByHeight:(float)statusBar;
-(id)specifiers;
-(id)contentViewForTopController;
-(BOOL)busy;
-(void)taskFinished:(id)finished;
-(void)addTask:(id)task;
-(BOOL)taskIsRunning:(id)running;
-(id)tasksDescription;
-(id)initWithTitle:(id)title identifier:(id)identifier;
-(id)readPreferenceValue:(id)value;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
@end

