/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSControlTableCell.h"

@class NSArray, NSDictionary;

@interface PSSegmentTableCell : PSControlTableCell {
	NSArray* _values;
	NSDictionary* _titleDict;
}
-(void)dealloc;
-(void)setValue:(id)value;
-(id)controlValue;
-(void)layoutSubviews;
-(void)setValues:(id)values titleDictionary:(id)dictionary;
-(BOOL)canReload;
-(void)setBackgroundView:(id)view;
-(id)titleLabel;
-(id)newControl;
-(void)prepareForReuse;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

