/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSControlTableCell.h"

@class UIView;

@interface PSSliderTableCell : PSControlTableCell {
	UIView* _disabledView;
}
-(void)layoutSubviews;
-(void)setValue:(id)value;
-(id)controlValue;
-(void)dealloc;
-(BOOL)canReload;
-(void)setCellEnabled:(BOOL)enabled;
-(id)titleLabel;
-(id)newControl;
-(void)prepareForReuse;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

