/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/Foundation.h>
#import "Preferences-Structs.h"


@interface PSSystemConfigurationDynamicStoreMISWatcher : NSObject {
	CFRunLoopSourceRef _scRunLoopSource;
	SCDynamicStoreRef _scDynamicStore;
	int _misState;
	int _misReason;
}
+(id)sharedManager;
-(void)sendStateUpdate;
-(void)readMISState:(int*)state andReason:(int*)reason;
-(void)getMISState:(int*)state andReason:(int*)reason;
-(void)dealloc;
-(id)init;
@end

