/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSTableCell.h"
#include <UIKit/UIKit.h>

@class PSTextView;

@interface PSTextViewTableCell : PSTableCell <UITextViewDelegate> {
	PSTextView* _textView;
}
@property(retain, nonatomic) PSTextView* textView;
-(void)drawTitleInRect:(CGRect)rect selected:(BOOL)selected;
-(UIEdgeInsets)textViewInsets;
-(BOOL)resignFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)textViewDidEndEditing:(id)textView;
-(void)_adjustTextView:(id)view updateTable:(BOOL)table withSpecifier:(id)specifier;
-(void)layoutSubviews;
-(void)cellRemovedFromView;
-(void)textViewDidChange:(id)textView;
-(void)setValue:(id)value;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

