/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSEditingPane.h"
#include <UIKit/UIKit.h>

@class UITableView, UITextField, PSTextEditingCell;

@interface PSTextEditingPane : PSEditingPane <UITableViewDelegate, UITableViewDataSource> {
	UITableView* _table;
	PSTextEditingCell* _cell;
	UITextField* _textField;
}
-(void)setPreferenceSpecifier:(id)specifier;
-(id)preferenceValue;
-(void)setPreferenceValue:(id)value;
-(BOOL)becomeFirstResponder;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

