/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSController.h"
#import <UIKit/UIKit.h>

@class PSSpecifier, PSRootController;

@interface PSViewController : UIViewController <PSController> {
	UIViewController<PSController>* _parentController;
	PSRootController* _rootController;
	PSSpecifier* _specifier;
}
-(void)statusBarWillAnimateByHeight:(float)statusBar;
-(BOOL)canBeShownFromSuspendedState;
-(void)formSheetViewDidDisappear;
-(void)formSheetViewWillDisappear;
-(void)popupViewDidDisappear;
-(void)popupViewWillDisappear;
-(void)handleURL:(id)url;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)pushController:(id)controller;
-(void)didWake;
-(void)didUnlock;
-(void)willUnlock;
-(void)didLock;
-(void)suspend;
-(void)willBecomeActive;
-(void)willResignActive;
-(id)readPreferenceValue:(id)value;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(id)specifier;
-(void)setSpecifier:(id)specifier;
-(void)dealloc;
-(id)rootController;
-(void)setRootController:(id)controller;
-(id)parentController;
-(void)setParentController:(id)controller;
@end

