/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */



@protocol PSViewControllerOffsetProtocol
-(float)verticalContentOffset;
-(void)setDesiredVerticalContentOffsetItemNamed:(id)named;
-(void)setDesiredVerticalContentOffset:(float)offset;
@end

